on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [bookworm, bullseye]
    env:
      VERSION: ${{ matrix.variant }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build targets
      run: make all
    - name: Push targets
      run: make tag
